### ISSUE TITLE
Can't activate it

### ISSUE THREAD

**Issue by sxe** [zzag/kwin-effects-cube#1]
When pressing the default (or assigned non default) shortcut nothing happens.

What I did:
Build it on archlinux, enabled it, restarted kwin just in case, added 3 more desktops (4 total now) and eve restart the whole machine, just to make absolutely sure it's not my session.

> System:
>   Host: main Kernel: 5.18.8-arch1-1 arch: x86_64 bits: 64 Desktop: KDE Plasma
>     v: 5.25.2 Distro: Arch Linux

> Graphics:
>   Device-1: NVIDIA GM204 [GeForce GTX 980] driver: nvidia v: 515.57
>   Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.2 driver: X:
>     loaded: nvidia unloaded: modesetting gpu: nvidia resolution:
>     1: 1920x1080~60Hz 2: 1920x1080~60Hz 3: 1280x1024~60Hz
>   OpenGL: renderer: NVIDIA GeForce GTX 980/PCIe/SSE2 v: 4.6.0 NVIDIA 515.57

Cheers

**Comment by jjgalvez** [comment]
I have the same issue. on Arch I looked through the journalctl and found 
```
module "QtQuick3D.Helpers" is not installed
```
however installing qt5-quick3d did not resolve the issue, and I can't find which package has the "QtQuick3D.Helpers" module

**Comment by sxe** [comment]
Ah you are right, get the same message, installing "qt5-quick3d" and restarting kwin "kwin_x11 --replace" fixes it for me!

**Comment by jjgalvez** [comment]
:) restarted kwin and now it works! very cool

**Comment by zzag** [comment]
Oh, looks like I need to add missing deps.

**Comment by zzag** [comment]
Updated the AUR package and added qt5-quick3d dep in README for Arch. No idea about Fedora and Ubuntu, quick search doesn't show any relevant packages.
