### ISSUE TITLE
install to ~/.local/ ?

### ISSUE THREAD

**Issue by kolAflash** [zzag/kwin-effects-cube#11]
Can I install this to `/home/USER/.local/` instead of installing it system wide?  
If yes, would you mind adding that to the README.md ?

Thanks!  
I love to get back the cube to impress my friends and myself :-)

**Comment by zzag** [comment]
You can, but you would need to adjust `QT_PLUGIN_PATH` so kwin looks for plugins in `~/.local/lib/qt/plugins`. Installing to `/usr` or `/usr/local` might be easier.
