### ISSUE TITLE
AUR package should use the commit with the latest tag when building

### ISSUE THREAD

**Issue by DolphyWind** [zzag/kwin-effects-cube#13]
Currently, the AUR package of this effect tries to build the effect from the latest commit. Since the last few commits require KDE6, it fails to build on KDE 5.27. To fix this, one can create a stable branch and merge every release with that branch, or treat the commit with the latest tag as the latest release. 

Using this command before attempting to generate CMake build files should be enough:
```git checkout $(git rev-list --tags --max-count=1)```

Thank you for creating this effect. Looks gorgeous.

**Comment by zjuyk** [comment]
Hi, I had discussed with zzag and provided an AUR package [kwin-effects-cube](https://aur.archlinux.org/packages/kwin-effects-cube) for Plasma 5 users.

**Comment by zjuyk** [comment]
@zzag Maybe we should update the README? This package works fine on my Plasma 5 Xorg.

**Comment by zzag** [comment]
Can you create a PR please?

**Comment by zjuyk** [comment]
Sure, please review #15
