### ISSUE TITLE
Update Fedora build instructions

### ISSUE THREAD

**Issue by Plaristote** [zzag/kwin-effects-cube#3]
Hey ! I just built this from Fedora 36, and it turns out some packages are missing from the dependencies list: 
kf5-ki18n-devel
libepoxy-devel

And two others are spelled wrong or no longer valid:
kf5-globalaccel-devel should be kf5-kglobalaccel-devel
kf5-xmlgui-devel should be kf5-kxmlgui-devel

**Comment by shawnk0723** [comment]
mine just broke after updating plasma to 5.25.4 today. It's gone from desktop effect option.

**Comment by goodguy00** [comment]
thank you very much. very helpful. now i can perfectly compile and install (as root). all fine. i can see the checkmark, i can enable it, but even after a reboot, it doesn't do anything. in contrary: after some minutes, my fedora37 desktop froze.

**Comment by Plaristote** [comment]
Didn't work for me either, actually. Same story: can see the checkmark, can enable it, but doesn't do anything.
I didn't notice any freeze, but maybe I just uninstalled it before it happened.

**Comment by X-m7** [comment]
It seems that both the Fedora and the Ubuntu build instructions don't appear to include the equivalent of `qt5-quick3d`, I'm on Arch with that installed and it works fine for me.

**Comment by zzag** [comment]
> Hey ! I just built this from Fedora 36, and it turns out some packages are missing from the dependencies list:

Fixed, thanks!

> It seems that both the Fedora and the Ubuntu build instructions don't appear to include the equivalent of qt5-quick3d, I'm on Arch with that installed and it works fine for me.

Added a note how to build qtquick3d from source code.
