### ISSUE TITLE
Ubuntu 22.10 (studio)

### ISSUE THREAD

**Issue by Epitheus** [zzag/kwin-effects-cube#4]
Seems like Qt5-QtQuick3D isnt in any repo of the system. Had to build it myself.

Another thing , but my quess is its a Qt issue , the skybox requires a very high resolution HDR image to look good.Which could be mentioned in the settings UI. Cant wait for Qt6 conversion so its less system heavy to load. 

And the Settings UI open window dialog is missing filter. Added it on my end and re-built. 

Oh and the buid instructions require "sudo" at the  - cmake --install build , so the last command should be : 
sudo cmake --install build

Thanks for bringing the cube back!

**Comment by zzag** [comment]
Added a note about building qtquick 3d from source code in README.md
