### ISSUE TITLE
ubable to assign a shortcut

### ISSUE THREAD

**Issue by guiodic** [zzag/kwin-effects-cube#5]
I'm unable to assign a shortcut. Once I did it, it disappears and never is applied

**Comment by zzag** [comment]
> Once I did it, it disappears and never is applied

Can you elaborate on what you mean by "disappears and never is applied"?

**Comment by guiodic** [comment]
It's never set. I was able only to set the "global" shortcut in the interface but it doesnt wor

**Comment by zzag** [comment]
How did you install the effect? Did you install the AUR package? or did you build it from source code? How many virtual desktops do you have?

**Comment by guiodic** [comment]
AUR package, 4 virtual desktops:
1 2
3 4

**Comment by zzag** [comment]
Do kwin's logs contain any error messages? You can check kwin's log by running `journalctl --follow --user-unit plasma-kwin_wayland` or `journalctl --follow --user-unit plasma-kwin_x11`

**Comment by guiodic** [comment]
Well, I restarted kwin (kwin --replace) and now it works! Thank you!

**Comment by zzag** [comment]
\o/
