### ISSUE TITLE
not working on ubuntu.

### ISSUE THREAD

**Issue by ghost** [zzag/kwin-effects-cube#6]
Hey, I just doing anything you said on read.me, and I did few extra step.
finally I got cube box on desktop effect, however if I press "key" that you said.
it's seem like it's doesn't working, by the way I tested on arch & manjaro both work fine.

**Comment by DoctorSubtilis** [comment]
same here

**Comment by Epitheus** [comment]
I`m using the cube with no issues on Ubuntu . 

My quess would be that you might be missing a library . in which case the cube builds , registers itself , but wont work.

If thats the case :

    QtQuick3D - name of the library , you will have to build it from source "qt-everywhere-src-5.15.6" or the kde patched one  

    - Step 1 : build.
    - Step 2 : copy   <your build folder>/qml/QtQuick3D  folder into /lib/x86_64-linux-gnu/qt5/qml folder 
    - Step 3 : for simplicity just copy anything  libQt5Quick3D*  from "<your build folder>/lib"  into  "/lib/x86_64-linux-gnu"
    - Step 4 : Enjoy the cube :D .

hope it helps.

PS : build steps missing  qtdeclarative5-dev  package . which i found out while building on freshly installed system.

**Comment by DoctorSubtilis** [comment]
This happens to me, when building  

`CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Quick" with any
  of the following names:

    Qt5QuickConfig.cmake
    qt5quick-config.cmake

  Add the installation prefix of "Qt5Quick" to CMAKE_PREFIX_PATH or set
  "Qt5Quick_DIR" to a directory containing one of the above files.  If
  "Qt5Quick" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)


-- Configuring incomplete, errors occurred!`

**Comment by Epitheus** [comment]
sudo apt-get install qtdeclarative5-dev

**Comment by DoctorSubtilis** [comment]
Thank you. Now I have another error message:  

```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
```
EDIT

Installed gettext. No more errors in this step.

**Comment by DoctorSubtilis** [comment]
Installed successfully. But not working (even after changing, in system settings, the keys). At least I don't understand how to do to get it working.

EDIT  

In your first post you said:  

> `copy   <your build folder>/qml/QtQuick3D`  

But I don't have such a folder in my build folder ...

**Comment by Epitheus** [comment]
There might be a misunderstanding  going in here . what i was talking about wasnt the cube build folder . but the Qt . In my 1st post there is even version which you need , the Qt is a development environment as well as set of libraries on which this project is running . Sadly tho , this version has to be downloaded as source on Ubuntu (at least i was unable to find pre-built lib). And youll have to build it yourself. There should be no issues tho , it just takes time ... think it was about 4h on 4 core system .

EDIT : 
BUT - thats me assuming that is the issue , to be more exact you should look into logs or maybe run the kwin from terminal to see the actual output . think there was even tool for that not sure tho . i prefer to just run    kwin --replace &   
in terminal to see the real time output. then i can see the error that pops when trying to activate the effect.

**Comment by zzag** [comment]
> Thank you. Now I have another error message:
> 
> ```
> CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
>   GETTEXT_MSGFMT_EXECUTABLE)
> ```
> 
> EDIT
> 
> Installed gettext. No more errors in this step.

Can you tell me what package you installed so I can put it in README

**Comment by zzag** [comment]
> Installed successfully. But not working (even after changing, in system settings, the keys). At least I don't understand how to do to get it working.
> 
> EDIT
> 
> In your first post you said:
> 
> > `copy   <your build folder>/qml/QtQuick3D`
> 
> But I don't have such a folder in my build folder ...

Can you check kwin's logs? `journalctl --user plasma-kwin_x11` or `journalctl --user plasma-kwin_wayland`. I suspect that you miss some qtquick runtime dependency

**Comment by zzag** [comment]
> I`m using the cube with no issues on Ubuntu .
> 
> My quess would be that you might be missing a library . in which case the cube builds , registers itself , but wont work.
> 
> If thats the case :
> 
> ```
> QtQuick3D - name of the library , you will have to build it from source "qt-everywhere-src-5.15.6" or the kde patched one  
> 
> - Step 1 : build.
> - Step 2 : copy   <your build folder>/qml/QtQuick3D  folder into /lib/x86_64-linux-gnu/qt5/qml folder 
> - Step 3 : for simplicity just copy anything  libQt5Quick3D*  from "<your build folder>/lib"  into  "/lib/x86_64-linux-gnu"
> - Step 4 : Enjoy the cube :D .
> ```
> 
> hope it helps.
> 
> PS : build steps missing qtdeclarative5-dev package . which i found out while building on freshly installed system.

That's a bummer ^^ :(

Do you know if it's available in some "official" ppa?

**Comment by Epitheus** [comment]
Sadly as far as my research went it seems like no , for some reason the library seems to be missing. i might be wrong tho , but on my 1st time build i looked for two days and didnt find it , ended up building it myself.

**Comment by DoctorSubtilis** [comment]
> > EDIT
> > Installed gettext. No more errors in this step.
> 
> Can you tell me what package you installed so I can put it in README

sudo apt install gettext

**Comment by DoctorSubtilis** [comment]
> kwin --replace &

```
kwin --replace &
[1] 9430
~$ OpenGL vendor string:                   Intel
OpenGL renderer string:                 Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL version string:                  4.6 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 4.60
Driver:                                 Intel
GPU class:                              Kaby Lake
OpenGL version:                         4.6
GLSL version:                           4.60
Mesa version:                           22.0.5
X server version:                       1.21.1
Linux kernel version:                   5.15
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
```

**Comment by DoctorSubtilis** [comment]
> Can you check kwin's logs? `journalctl --user plasma-kwin_x11` or `journalctl --user plasma-kwin_wayland`. I suspect that you miss some qtquick runtime dependency

Unfortunately:

`duns@duns-neon:~$ journalctl --user plasma-kwin
Failed to add match 'plasma-kwin': Argomento non valido
duns@duns-neon:~$ journalctl --user plasma-kwin-x11
Failed to add match 'plasma-kwin-x11': Argomento non valido
duns@duns-neon:~$ journalctl --user kwin-x11
Failed to add match 'kwin-x11': Argomento non valido
duns@duns-neon:~$ journalctl --user kwin
Failed to add match 'kwin': Argomento non valido
duns@duns-neon:~$ journalctl --user plasma-kwin_x11  
Failed to add match 'plasma-kwin_x11': Argomento non valido
`
invalid argument

**Comment by Epitheus** [comment]
if you did the replace method , just press the set up key to activate the effect , so you can see the actual error pop in the terminal.

**Comment by DoctorSubtilis** [comment]
> just press the set up key to activate the effect , so you can see the actual error pop in the terminal.

done:

```
 kwin --replace &
::1             ff02::1         ip6-allnodes    ip6-localhost   localhost       
duns-neon       ff02::2         ip6-allrouters  ip6-loopback    
duns@duns-neon:~$ kwin --replace &s
[2] 9889
s: comando non trovato
```
command not found (non trovato)

**Comment by Epitheus** [comment]
typo in command mate :D

**Comment by DoctorSubtilis** [comment]
???

**Comment by Epitheus** [comment]
duns@duns-neon:~$ kwin --replace &s     < ----    you put "s" on the end , thats why you got that error . 

its just ->      kwin --replace &  
     
Then use the shortcut to activate the effect so you can see the error that pops in as new text in your terminal.

EDIT : just cleaned this message up a little .

**Comment by DoctorSubtilis** [comment]
ok, sorry :) 
this is the output:  

Failed to load QUrl("file:///usr/share/kwin/effects/cube/qml/main.qml"): (file:///usr/share/kwin/effects/cube/qml/main.qml:8:1: module "QtQuick3D" is not installed
    import QtQuick3D 1.15
    ^)

**Comment by Epitheus** [comment]
Yup , its the missing library QtQuick3D as stated in my 1st post in this topic.

Sadly seems like its not available in any "official" PPA , or at least i was unable to find it  , so built it myself.

**Comment by DoctorSubtilis** [comment]
I see. I will try, but not today.
Thank you!

EDIT

How should I do to build QtQuick3D?

**Comment by Epitheus** [comment]
> I see. I will try, but not today. Thank you!
> 
> EDIT
> 
> How should I do to build QtQuick3D?

I dont think this is a proper place to discuss that .... but : 

 In extracted folder : 

    ./configure -release -opensource -confirm-license -prefix <build folder>
     make -j<num of cores>
     make install

i hope im not breaking any rules now , and sorry for the late answer .

**Comment by erck63** [comment]
Bonjour 
cela ne fonctionne pas sur kubuntu 22.10
j’ai suivi les commandes et cela semble être ok mais ctrl+C ne déclenche rien
ni sur wayland ni sur X11
```
On Ubuntu

sudo apt install cmake extra-cmake-modules kwin-dev \
    libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev \
    libkf5windowsystem-dev libkf5globalaccel-dev libkf5xmlgui-dev qtbase5-dev

After you installed all the required dependencies, you can build the effect:

git clone https://github.com/zzag/kwin-effects-cube.git
cd kwin-effects-cube
cmake -B build -S . \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build build --parallel
cmake --install build

```
Donc je commence le pas à pas explicatif

```
kubu@kubu-MS-7821:~$ sudo apt install cmake extra-cmake-modules kwin-dev     libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev     libkf5windowsystem-dev libkf5globalaccel-dev libkf5xmlgui-dev qtbase5-dev
[sudo] Mot de passe de kubu : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
cmake est déjà la version la plus récente (3.24.2-1ubuntu1).
extra-cmake-modules est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
kwin-dev est déjà la version la plus récente (4:5.26.4-0ubuntu1~ubuntu22.10~ppa1).
libkf5config-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
libkf5configwidgets-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
libkf5coreaddons-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
libkf5windowsystem-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
libkf5globalaccel-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
libkf5xmlgui-dev est déjà la version la plus récente (5.100.0-0ubuntu1~ubuntu22.10~ppa1).
qtbase5-dev est déjà la version la plus récente (5.15.6+dfsg-1).
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  dctrl-tools dh-dkms dkms
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 9 non mis à jour.
kubu@kubu-MS-7821:~$ 
```

```
kubu@kubu-MS-7821:~$ git clone https://github.com/zzag/kwin-effects-cube.git
Clonage dans 'kwin-effects-cube'...
remote: Enumerating objects: 363, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 363 (delta 0), reused 1 (delta 0), pack-reused 357
Réception d'objets: 100% (363/363), 1.05 Mio | 10.19 Mio/s, fait.
Résolution des deltas: 100% (250/250), fait.
kubu@kubu-MS-7821:~$
```

```
kubu@kubu-MS-7821:~$ cd kwin-effects-cube
kubu@kubu-MS-7821:~/kwin-effects-cube$ 

```
```
kubu@kubu-MS-7821:~/kwin-effects-cube$ cmake -B build -S . \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:26 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5Config: /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.100.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.100.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.100.0") 
-- Found KF5GlobalAccel: /usr/lib/x86_64-linux-gnu/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (found version "5.100.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.100.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.100.0") 
-- Found KF5XmlGui: /usr/lib/x86_64-linux-gnu/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.100.0") 
-- Found KF5: success (found suitable version "5.100.0", minimum required is "5.94.0") found components: Config ConfigWidgets CoreAddons GlobalAccel I18n WindowSystem XmlGui 
-- Found epoxy: /usr/lib/x86_64-linux-gnu/libepoxy.so (found version "1.5.10") 
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindXCB.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindXCB.cmake:67 (ecm_find_package_version_check)
  CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.15") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.15") found components: XCB 
-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.100.0)
 * KF5Codecs (required version >= 5.100.0)

-- The following REQUIRED packages have been found:

 * ECM
 * Qt5Network (required version >= 5.15.6)
 * Qt5Qml (required version >= 5.15.6)
 * Qt5QmlModels (required version >= 5.15.6)
 * Qt5Quick
 * Qt5 (required version >= 5.15.0)
 * KF5GlobalAccel (required version >= 5.94.0)
 * Gettext
 * KF5I18n (required version >= 5.94.0)
 * KF5XmlGui (required version >= 5.94.0)
 * KF5 (required version >= 5.94.0)
 * epoxy
 * XCB, X protocol C-language Binding, <https://xcb.freedesktop.org/>
 * Qt5DBus (required version >= 5.15.2)
 * KF5Config (required version >= 5.98.0)
 * Qt5Core (required version >= 5.15.2)
 * KF5CoreAddons (required version >= 5.98.0)
 * Qt5Gui (required version >= 5.15.2)
 * KWinEffects (required version >= 5.25.0)
 * KWinDBusInterface

-- Configuring done
-- Generating done
-- Build files have been written to: /home/kubu/kwin-effects-cube/build
kubu@kubu-MS-7821:~/kwin-effects-cube$ 
```

```
kubu@kubu-MS-7821:~/kwin-effects-cube$ cmake --build build --parallel
[ 11%] Automatic MOC for target kwin_cube_config
[ 11%] Automatic MOC for target kwin4_effect_cube
[ 11%] Built target kwin_cube_config_autogen
[ 23%] Generating ui_cubeeffectkcm.h
[ 23%] Generating kwineffects_interface.cpp, kwineffects_interface.h
[ 29%] Generating cubeconfig.h, cubeconfig.cpp
[ 29%] Built target kwin4_effect_cube_autogen
[ 35%] Generating cubeconfig.h, cubeconfig.cpp
[ 41%] Generating kwineffects_interface.moc
[ 47%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/cubeeffect.cpp.o
[ 52%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/kwin4_effect_cube_autogen/mocs_compilation.cpp.o
[ 58%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/kwineffects_interface.cpp.o
[ 64%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/main.cpp.o
[ 70%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/cubeeffectkcm.cpp.o
[ 76%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/kwin_cube_config_autogen/mocs_compilation.cpp.o
[ 82%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/cubeconfig.cpp.o
[ 88%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/cubeconfig.cpp.o
[ 94%] Linking CXX shared module kwin4_effect_cube.so
[100%] Linking CXX shared module kwin_cube_config.so
[100%] Built target kwin4_effect_cube
[100%] Built target kwin_cube_config
kubu@kubu-MS-7821:~/kwin-effects-cube$ 
```

```
kubu@kubu-MS-7821:~/kwin-effects-cube$ cmake --install build
-- Install configuration: "Release"
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/kwin4_effect_cube.so
CMake Error at build/src/cmake_install.cmake:52 (file):
  file INSTALL cannot copy file
  "/home/kubu/kwin-effects-cube/build/src/kwin4_effect_cube.so" to
  "/usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/kwin4_effect_cube.so":
  Permission denied.
Call Stack (most recent call first):
  build/cmake_install.cmake:47 (include)
kubu@kubu-MS-7821:~/kwin-effects-cube$
```

```
kubu@kubu-MS-7821:~/kwin-effects-cube$ sudo cmake --install build
-- Install configuration: "Release"
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/kwin4_effect_cube.so
-- Up-to-date: /usr/share/kwin/effects/cube/qml
-- Installing: /usr/share/kwin/effects/cube/qml/Cube.qml
-- Installing: /usr/share/kwin/effects/cube/qml/CubeCameraController.qml
-- Installing: /usr/share/kwin/effects/cube/qml/DesktopView.qml
-- Installing: /usr/share/kwin/effects/cube/qml/main.qml
-- Installing: /usr/share/kwin/effects/cube/qml/CubeFace.qml
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/configs/kwin_cube_config.so
kubu@kubu-MS-7821:~/kwin-effects-cube$ 
```

donc je vois bien dans ma configuration du système/ comportement de l’espace de travail/ effets de bureau /gestion des fenêtres /Cube
mais avec meta+C rien ne se passe
essayer de passer sous x11 ou wayland de rebooter l’ordi rien de plus

**Comment by Epitheus** [comment]
On dirait qu'il est construit correctement, peut-être le QtQuick3D manquant, mieux vérifier le journal comme mentionné dans le post précédent par zzag ou faire 

kwin --replace 

dans le terminal et voir la sortie directe lorsque vous utilisez le meta+C.

traduit par Google traduction.

**Comment by erck63** [comment]
merci de votre réponse rapide
mais idem que DocteurSubtilis
```
kubu@kubu-MS-7821:~$ journalctl --user plasma-kwin_wayland
Failed to add match 'plasma-kwin_wayland': Argument invalide
kubu@kubu-MS-7821:~$ journalctl --user plasma-kwin
Failed to add match 'plasma-kwin': Argument invalide
kubu@kubu-MS-7821:~$ 
```
quel est le chemin  pour le journalctl ?
et kwin --replace& re démarre kwin 
je perds la konsole et firefox 
ouverture konsole
appui sur ctrl+c
```
kubu@kubu-MS-7821:~$ 
::1              ff00::0          ff02::2          ip6-allrouters   ip6-localnet     ip6-mcastprefix  localhost        
fe00::0          ff02::1          ip6-allnodes     ip6-localhost    ip6-loopback     kubu-MS-7821     
kubu@kubu-MS-7821:~$ sC

```
je n’ais pas de message

**Comment by Epitheus** [comment]
ne mettez pas le raccourci sur ctrl+c (dans le terminal cela signifie annuler le travail, mais meta+c -> la fenêtre comme icône sur votre clavier +c) ,

et franchement aucune idée
à propos de KUbuntu, essayez peut-être 

   setsid kwin --replace &  

"setsid" laissera kwin fonctionner même si vous fermez le terminal.


Traduit par Google traduction.

**Comment by erck63** [comment]
merci pour vos retours
houps pour le ctrl + c
c’est une erreur de ma part j’ai Méta+c bien sur
"setsid" n’a rien changé 
pour apercevoir le cube
je vais attendre quelque chose de plus solide
bon courage !

**Comment by zzag** [comment]
Added missing dependencies in README.md and added instructions how to build QtQuick 3D from source code. https://github.com/zzag/kwin-effects-cube/commit/2d833e28cce924e431089cf951b2991e753580d6
